### ISSUE TITLE
review transform_om_oc

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/BlueCarbon#11]
Hi

I've started reviewing `transform_om_oc` in this branch: https://github.com/EcologyR/BlueCarbon/tree/review_transform_om_oc

If I understood correctly, I think it would be good to have a function estimating the linear model and predicting from it. Then have another function that does this for as many sites, etc as desired

One Q: is there any reason why predictions are done by hand (int + slope*x) rather than using predict? Otherwise I think it'd be better to use predict

**Comment by NPJuncal** [comment]
Hi!
the only reason to do the predictions by hand was my ignorance of the function predict :)

**Comment by Pakillo** [comment]
Ah hahaha ok :) Let's change it then

**Comment by Julenasti** [comment]
Algunas sugerencias aqui:
- Esto estaría bien dejar que el usuario lo pueda modificar como un parámetro de la función. Podemos poner el the default ese pero que el usuario lo pueda modificar (https://r4ds.had.co.nz/functions.html#function-arguments): https://github.com/EcologyR/BlueCarbon/blob/f041b546c8e352982567e526927fda72b3c5efa0/R/transform_om_oc.R#L15
- Aquí podemos dejar que no solo sea data frame. También por ejemplo un tibble (https://tibble.tidyverse.org/reference/is_tibble.html): https://github.com/EcologyR/BlueCarbon/blob/f041b546c8e352982567e526927fda72b3c5efa0/R/transform_om_oc.R#L20
- En esta parte me pregunto si los nombres que le das son demasiado restrictivos. Es decir sí o sí tienen que llamarse así. Quizás estaría bien que tuviera que tener esas variables pero que el usuario los pueda especificar en forma de argumento: https://github.com/EcologyR/BlueCarbon/blob/f041b546c8e352982567e526927fda72b3c5efa0/R/transform_om_oc.R#L23
- En esta parte me está dando el toc y bueno como antes o después creo que conviene hacerlo aquí unas sugerencias de escritura de código que está guay seguirlas (http://adv-r.had.co.nz/Style.html, pero tengo que admitir que yo tampoco sigo siempre todas 😆 ): https://github.com/EcologyR/BlueCarbon/blob/f041b546c8e352982567e526927fda72b3c5efa0/R/transform_om_oc.R#L36
- En los for en vez de `1:length(x)`, que es lo más común, es más robusto utilizar `seq_along(x)` para evitar problemas cuando `length(x) == 0` (https://adv-r.hadley.nz/control-flow.html#common-pitfalls): https://github.com/EcologyR/BlueCarbon/blob/f041b546c8e352982567e526927fda72b3c5efa0/R/transform_om_oc.R#L51
-

**Comment by Pakillo** [comment]
Gracias Julen. Muchas de las cosas que comentas las he ido cambiando aquí https://github.com/EcologyR/BlueCarbon/compare/master...review_transform_om_oc. Si queréis hago pull request ya, por integrarlo, pero aún no he terminado. Si no pues lo hablamos mañana in situ :)

**Comment by NPJuncal** [comment]
Faltan los nombres y eliminar dependencia a paquete broom (sugerencias Julen 3 and 9)

**Comment by NPJuncal** [comment]
function predict no funciona
ademas ver si podemos especificar un numero minimo de muestras para la funcion fit_models

despues hay que crear una funcion grande con todas ellas

**Comment by NPJuncal** [comment]
Funcion generada (funciona), the devuelve el dataframe y un plot con el carbono estimado. Tambien se han añadido comentarios en el codigo y repasado la documentacion de Roxygen
