### ISSUE TITLE
estimate_h

### ISSUE THREAD

**Issue by NPJuncal** [EcologyR/BlueCarbon#20]
especificar nombres para que el ususario pueda cambiarlos

by default los usados en estimate_stock

**Comment by NPJuncal** [comment]
Done, testear y documentar

**Comment by NPJuncal** [comment]
check that the samples of each core are provided in order

**Comment by NPJuncal** [comment]
@Pakillo @Julenasti  In estimate_h there are two small functions defined withing the function, shoud we take them out, like in the other main functions?

**Comment by Julenasti** [comment]
Hi Nerea, yes I'd follow the same approach as the others and take them out of the main function. I think it's easier to understand (e.g. https://github.com/EcologyR/BlueCarbon/blob/master/R/estimate_oc.R)
This is looking very good!

**Comment by NPJuncal** [comment]
Function working and ready
