### ISSUE TITLE
estimate_stock

### ISSUE THREAD

**Issue by NPJuncal** [EcologyR/BlueCarbon#21]
modificar los nombres de las columnas por los usuarios

modelos para predecir stock en cores cortos: log(massa accumulada)-profundidad (exp() despues!!)

usar predict para sacar el stock y el se de la prediccion

**Comment by NPJuncal** [comment]
Hola @Julenasti
ya cambie el codigo para lapply. Podrias echarle un ojo cuando puedas?

para probarlo puedes usar el dataset ejemplo bluecarbon_data, pero tendrias que pasarlo primero por la funcion transform_om_oc para tener datos de carbono organico

:)

**Comment by Julenasti** [comment]
Qué bien Nerea!! Veo que lo has pillado enseguida 😃 
El miércoles lo miro seguro y si antes tengo algún huequito antes

**Comment by Julenasti** [comment]
Hola Nerea,

Te he hecho unos comentarios en la rama principal. Empieza con un pull request para trabajar sobre ello. Algunas sugerencias/dudas que me han surgido:
- Sugiero llamarme a la función `estimate_oc_stock` por ser consistente con lo anterior.
- En la description, standardisation depth: creo que no queda claro lo que significa
-

**Comment by Julenasti** [comment]
Hola Nerea! Era para saber cómo vas con los progresos y si necesitas que te eche una mano con algo. Cuando puedas, no worries!

**Comment by NPJuncal** [comment]
checkear que las muestras estan por orden

**Comment by NPJuncal** [comment]
It checks that the samples are in order.
