### ISSUE TITLE
Depth y Timeframe puede que no funcionen...

### ISSUE THREAD

**Issue by NPJuncal** [EcologyR/BlueCarbon#24]
Depth y Timeframe se repiten en funciones internas. No se como va....

**Comment by Julenasti** [comment]
No entiendo el issue. Nos puedes dar un poco más de información porfa?

**Comment by NPJuncal** [comment]
En ambas funciones el usuario puede escoger la profundidad a la que se calcula el stock o el time frame que se usa para estimar el flujo medio. Este parametro se necesita para la funcion general pero tambien para alguna de las funciones internas, lo he especificado indicando que el parametro de las internas sera siempre igual al de la global. Pero no se si funciona. De todas formas estas dos funciones estan sin terminar... empece a sacar los loops y no acabe...

**Comment by NPJuncal** [comment]
Perfecto!
