### ISSUE TITLE
functions defined within another function

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/BlueCarbon#25]
I'm revising `transform_om_oc` and I found a few functions that are defined within the big function.
While that's technically correct and I can see the benefit (mostly that we don't need to provide arguments to the inner functions, e.g. see [this](https://stackoverflow.com/questions/62359099/function-inside-function-in-r)), I think the disadvantages greatly outweigh that minor advantage.

First, the function is very long and very hard to navigate, with functions defined within functions within other function... Also inner functions are not exposed and thus much harder to test individually. And it's also slower than having functions defined outside, because inner functions are redefined every time the big function is called.

Hence I'm planning to take the inner functions (fit_models, choose_model, predict_oc, etc) outside. Is that fine for you?

**Comment by NPJuncal** [comment]
Yes. No problem.

**Comment by Pakillo** [comment]
No, I mean, the functions will keep existing, but I'll take them out of the `transform_om_oc` function where they are currently defined within. Those functions will be internal, the user will not see them nor see them anytime. It's just a restructuring of the code to ease development

**Comment by Julenasti** [comment]
Ah, OK, perfect! And where should they go? Or what should the directory/script structure look like now?

**Comment by Pakillo** [comment]
I'll move those functions below `transform_om_oc` in the same Rscript. I'm in the middle of refactoring all that, please do not change that R file to avoid merge conflicts. Thanks
