### ISSUE TITLE
Estimating organic carbon from organic matter: lm(log) vs lognormal glm

### ISSUE THREAD

**Issue by Pakillo** [EcologyR/BlueCarbon#28]
``` r
download.file("https://github.com/EcologyR/BlueCarbon/raw/master/data/bluecarbon_data.rda",
              destfile = "bluecarbon_data.rda", mode = "wb")
load("bluecarbon_data.rda")

df <- bluecarbon_data[, c("om", "oc")]
df <- df[complete.cases(df), ]

plot(oc ~ om, df)
```

![](https://i.imgur.com/13nNyTb.png)

``` r
plot(log(oc) ~ log(om), df)

library(visreg)
```

![](https://i.imgur.com/GJUtrEt.png)

``` r
library(DHARMa)
#> This is DHARMa 0.4.6. For overview type '?DHARMa'. For recent changes, type news(package = 'DHARMa')

## 1. Linear model

m1 <- lm(oc ~ om, data = df)
summary(m1)
#> 
#> Call:
#> lm(formula = oc ~ om, data = df)
#> 
#> Residuals:
#>     Min      1Q  Median      3Q     Max 
#> -3.5660 -0.3916 -0.1385  0.2927  7.1870 
#> 
#> Coefficients:
#>             Estimate Std. Error t value Pr(>|t|)    
#> (Intercept)  0.11552    0.06694   1.726   0.0852 .  
#> om           0.30743    0.01399  21.969   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.7842 on 387 degrees of freedom
#> Multiple R-squared:  0.555,  Adjusted R-squared:  0.5538 
#> F-statistic: 482.6 on 1 and 387 DF,  p-value: < 2.2e-16
visreg(m1)
```

![](https://i.imgur.com/JoSU5iL.png)

``` r
simulateResiduals(m1, plot = TRUE)
```

![](https://i.imgur.com/PGJWJO7.png)

    #> Object of Class DHARMa with simulated residuals based on 250 simulations with refit = FALSE . See ?DHARMa::simulateResiduals for help. 
    #>  
    #> Scaled residual values: 0.712 0.16 0.968 0.804 0.964 1 1 1 0.996 0.628 0.964 0.988 0.896 0.848 0.732 0.732 0.724 0.996 0.94 0.968 ...
    summary(fitted(m1))
    #>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    #>  0.2717  0.7778  1.0920  1.2985  1.4930  9.0190
    summary(df$oc, na.rm = TRUE)
    #>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    #>  0.05172  0.52067  1.10691  1.29848  1.59969 12.43664
    plot(df$oc, fitted(m1), xlim = c(0, 4), ylim = c(0, 4))
    abline(a = 0, b = 1, col = "red")

![](https://i.imgur.com/0LVnG4I.png)

``` r
cor(df$oc, fitted(m1))
#> [1] 0.7449687


## 2. lm(log(oc))

m2 <- lm(log(oc) ~ log(om), data = df)
summary(m2)
#> 
#> Call:
#> lm(formula = log(oc) ~ log(om), data = df)
#> 
#> Residuals:
#>      Min       1Q   Median       3Q      Max 
#> -1.76185 -0.36345  0.01436  0.40042  1.13577 
#> 
#> Coefficients:
#>             Estimate Std. Error t value Pr(>|t|)    
#> (Intercept) -1.39163    0.05390  -25.82   <2e-16 ***
#> log(om)      1.14084    0.04118   27.70   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Residual standard error: 0.5207 on 387 degrees of freedom
#> Multiple R-squared:  0.6647, Adjusted R-squared:  0.6639 
#> F-statistic: 767.3 on 1 and 387 DF,  p-value: < 2.2e-16
visreg(m2)
```

![](https://i.imgur.com/WuyQ5ZI.png)

``` r
simulateResiduals(m2, plot = TRUE)
```

![](https://i.imgur.com/ul13Efx.png)

    #> Object of Class DHARMa with simulated residuals based on 250 simulations with refit = FALSE . See ?DHARMa::simulateResiduals for help. 
    #>  
    #> Scaled residual values: 0.876 0.004 0.976 0.952 0.936 0.972 0.928 0.924 0.972 0.868 0.96 0.972 0.972 0.928 0.792 0.792 0.88 0.96 0.936 0.948 ...
    summary(exp(fitted(m2)))
    #>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    #>  0.1148  0.5969  0.9294  1.1967  1.3762 11.5698
    summary(df$oc, na.rm = TRUE)
    #>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
    #>  0.05172  0.52067  1.10691  1.29848  1.59969 12.43664
    plot(df$oc, exp(fitted(m2)), xlim = c(0, 4), ylim = c(0, 4))
    abline(a = 0, b = 1, col = "red")

![](https://i.imgur.com/bZ7gADk.png)

``` r
cor(df$oc, fitted(m2))
#> [1] 0.7052702


## 3. lognormal glm

library(VGAM)
#> Loading required package: stats4
#> Loading required package: splines
m3 <- vglm(oc ~ log(om), data = df, family = lognormal)
summary(m3)
#> 
#> Call:
#> vglm(formula = oc ~ log(om), family = lognormal, data = df)
#> 
#> Coefficients: 
#>               Estimate Std. Error z value Pr(>|z|)    
#> (Intercept):1 -1.39163    0.05376  -25.89   <2e-16 ***
#> (Intercept):2 -0.65519    0.03585  -18.27   <2e-16 ***
#> log(om)        1.14084    0.04108   27.77   <2e-16 ***
#> ---
#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
#> 
#> Names of linear predictors: meanlog, loglink(sdlog)
#> 
#> Log-likelihood: -262.1058 on 775 degrees of freedom
#> 
#> Number of Fisher scoring iterations: 7 
#> 
#> No Hauck-Donner effect found in any of the estimates
plot(fitted(m3) ~ log(df$om))
```

![](https://i.imgur.com/1Ez6AuT.png)

``` r
summary(fitted(m3))
#>        V1         
#>  Min.   : 0.1314  
#>  1st Qu.: 0.6830  
#>  Median : 1.0636  
#>  Mean   : 1.3695  
#>  3rd Qu.: 1.5749  
#>  Max.   :13.2402
summary(df$oc, na.rm = TRUE)
#>     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
#>  0.05172  0.52067  1.10691  1.29848  1.59969 12.43664
plot(df$oc, fitted(m3), xlim = c(0, 4), ylim = c(0, 4))
abline(a= 0, b = 1, col = "red")
```

![](https://i.imgur.com/EfJiQba.png)

``` r
cor(df$oc, fitted(m3))
#>           [,1]
#> [1,] 0.7335657
```

<sup>Created on 2023-05-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Pakillo** [comment]
lognormal models slightly better, even though lm(log) don't perform bad. lm models on absolute scales do perform badly.
See #26

**Comment by Julenasti** [comment]
Very nice tests Paco! Thanks!!
Yes, I agree using a lognormal or lm(log)
