### ISSUE TITLE
Function for core decompaction

### ISSUE THREAD

**Issue by NPJuncal** [EcologyR/BlueCarbon#32]
I have separated linear from exponential core decompaction, as they requiere different data.

Linear decompaction is almost done. Exponential does not work and may need to be redone.

Next steps:

- Document linear decompaction
- Test for linear decompaction
- Make exponential decompaction function from scratch

**Comment by Julenasti** [comment]
Hi Nerea,

Good progress!! 👏Let us know if we can help you with any specific tasks

Taking a brief look at the README, I would suggest keeping it as simple as possible and then we can make vignettes explaining specific jobs like here: https://github.com/VeruGHub/easyclimate/

**Comment by NPJuncal** [comment]
issue included in especific issue for the function

**Comment by NPJuncal** [comment]
issue included in especific issue for the function
