### ISSUE TITLE
calcular a mano el resultado

### ISSUE THREAD

**Issue by NPJuncal** [EcologyR/BlueCarbon#4]
https://github.com/EcologyR/BlueCarbon/blob/d9bdd2c858566b1e41ca9da0d91e6d382e8e273e/tests/testthat/test-estimate_flux.R#L7

**Comment by Julenasti** [comment]
@NPJuncal si neceistas que revise algo o que le eche un vistazo algo me dices. Porfa, mencióname en el issue si es el caso porque sino no llegan los mensajes
