### ISSUE TITLE
El calculo de la altura (h) tiene que tener en cuenta el tamaño de la muestra inicial

### ISSUE THREAD

**Issue by NPJuncal** [EcologyR/BlueCarbon#7]
La altura final de la muestra se estima como la distancia intermedia entre el centro de las muestras iniciales. Pero algunas muestras son mas largas que otras. Esto se tiene que tener en cuenta. Respetar la altura inicial de la muestra y calcular el punto intermedio entre el inicio de la muestra y el final de la anterior, no el centro.

Chequear que el final de una muestra no es igual al inicio de la siguiente (si es asi, la altura es igual a la longitud de la muestra). Si no, chequear que las muestras no estan solapadas (esto no deberia ser posible... a no ser que hagan pools de cores)

**Comment by Pakillo** [comment]
Love the workflow! Raise issue identifying the problem, classify type of issue, assign someone to fix it (you), and fix with commit referencing the issue. All very clear and linked

:clap: :clap:  

P.S. ICYMI you can even close the issue with a commit, if you include "Close #7" in the commit message
